### ISSUE TITLE
WebUI submodules import

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#281] opened 2015-07-29 08:02 UTC
The new submodules in the WebUI make the broker log a Warning:

```
[1438156709] WARNING: [broker-master] Cannot import webui..module : No module named submodules.metamodule
[1438156709] WARNING: [broker-master] Trying to load '/var/lib/shinken/modules/webui' as an (very-)old-style shinken "module" : by adding its path to sys.path. This can be (very) bad in case of name conflicts within the files part of /var/lib/shinken/modules/webui and others top-level python modules; I'll try to limit that.
[1438156709] INFO: [broker-master] Correctly loaded webui as a very old-style shinken module :s

```

**Note:** this log is a simple alert on WebUI module importation by the broker ... at the end, the WebUI is started and runs correctly!

**Comment by mohierf** [comment] 2015-07-29 08:20
Source of the WARNING log is in Shinken *modulesmanager.py*, function *try_best_load*. 

This function is called twice : 
- first with  the module name
- twice with `.module`as module name and module name as `package`

```
    def try_best_load(cls, name, package=None):
        try:
            mod = importlib.import_module(name, package)
        except Exception as err:
            logger.warning("Cannot import %s : %s",
                           '%s.%s' % (package, name) if package else name,
                           err)
            return
```

**Comment by maethor** [comment] 2015-07-30 10:12
Don't assign this to me. For me, all this module management is pure magic :D 

Stupid question: did you find a documentation somewhere that explain how to make a "new style" module ?

**Comment by mohierf** [comment] 2015-07-30 12:39
You are right ... I assigned this issue to you if you had an idea about it. But, no, I did not found any info about what are old style, new-old style, old-new style ... modules :-)

**Comment by Simage** [comment] 2015-07-31 05:40
Issue appears to be due to the submodules python module not being found in the python path, as such it falls back to an older import mechanism that adds the shinken modules path (too many different definitions of module) to sys.path allowing it to resolve submodules.metamodule. I suspect that the issue is easiest resolved by simply changing the sub modules to use relative imports to pull the parent class into the module

**Closed** 2015-07-31 06:09 UTC
Labels: development
