### ISSUE TITLE
WebUI2 and spaces in names

### ISSUE THREAD

**Issue by pedrojimenez** [shinken-monitoring/mod-webui#474] opened 2016-04-13 15:34 UTC
Hi we have faced a undesired behaviour in the WebUI2 when accessing the HostGroups via its tab. We have created 2 hostgroups with identical members but with different **hostgroup_name**, one of them with spaces.

Here is the code of the configuration:
<pre>
define hostgroup {
    alias    HG_NO_SPACES_ALIAS
    hostgroup_name    HG_NO_SPACES
    members    host1, host2, host3, host4
}

define hostgroup {
    alias    HG WITH SPACES ALIAS
    hostgroup_name    HG WITH SPACES
    members    host1, host2, host3, host4
}
</pre>

In the WebUI tab one of the hostgroups is not resolving its content hosts, the one with spaces:

![seleccion_206](https://cloud.githubusercontent.com/assets/1044532/14498109/a2091cb0-0199-11e6-95c3-27e8128c94dd.png)

Searching in the code i have seen that the search string is splitted by spaces ... and after this process is stripped and resplitted again: [Link](https://github.com/shinken-monitoring/mod-webui/blob/develop/module/datamanager.py#L318-L325)

This is part of the debug where you can see the problem with spaces and hostgroup names ... 
<pre>
>>>>>>>>>Initial: type:host hg:HG_NO_SPACES
xxxxxxxxxxx [u'type:host', u'hg:HG_NO_SPACES']

>>>>>>>>>Initial: type:host hg:HG WITH SPACES
xxxxxxxxxxx [u'type:host', u'hg:HG', u'WITH', u'SPACES']
</pre>

But it also occurs searching for host names (default), and the really amazing: the split level is  increased if extra spaces are submitted
<pre>
>>>>>>>>> Initial:  test host (single space between the words)
xxxxxxxxxxx [u'test', u'host']

>>>>>>>>> Initial:  test    host (3 spaces between the words)
xxxxxxxxxxx [u'test', u'', u'', u'',u'host']
</pre>

I think all the related searches (servicegroup / tags / minemap) are suffering the same problems.
The Shinken/Nagios configuration options allows to create hosts, hostgroups ... with spaces in their names. Maybe an alternate scape option for searhes with double quotation marks could be implemented ... In example
<pre>
search: type:host hg:"HG WITH SPACES"
</pre>

**Comment by mohierf** [comment] 2016-04-15 11:01
You are right ... search options should be improved. I will a look for this ...

**Comment by pedrojimenez** [comment] 2016-04-15 11:06
Thx @mohierf

**Comment by dgilm** [comment] 2016-04-15 11:20
If a can make a suggestion, use a dict for the search argument and the method will drastically reduce its complexity. Playing with strings is almost never a good idea...
https://github.com/shinken-monitoring/mod-webui/blob/develop/module/datamanager.py#L303

**Comment by mohierf** [comment] 2016-04-18 17:58
This should be fixed with the last version 2.4 I will publish (still in the develop branch ...). Please confirm and re-open this issue if the problem is not fixed ...

**Comment by pedrojimenez** [comment] 2016-04-20 07:11
Hi again,
I have updated WebUI2 to v2.4.0 and have found another problem. The "host-groups" tab is not working by now. It does not show any info about any hostgroup created. 

I have used the same previous config:
<pre>
define hostgroup {
    alias    HG_NO_SPACES_ALIAS
    hostgroup_name    HG_NO_SPACES
    members    host1, host2, host3, host4
}

define hostgroup {
    alias    HG WITH SPACES ALIAS
    hostgroup_name    HG WITH SPACES
    members    host1, host2, host3, host4
}
</pre>

The information in the "host-groups" tab showing empty members for both:
![seleccion_216](https://cloud.githubusercontent.com/assets/1044532/14665958/00ca1488-06d7-11e6-90be-1d362e158313.png)

Accessing any of the host details, the related information about its "groups" is correctly showed. Also checked with another UI (Thruk) and the hostgroup is correct with 4 members, and the HG and members are correct:
![hgs_detail](https://cloud.githubusercontent.com/assets/1044532/14665975/15c56464-06d7-11e6-90d4-55842d1c516c.png)


NOTE: I think that but the problem still persists cause the link showed by the browser will point to a link with spaces and no quotation marks:
![capturashinkenhgs](https://cloud.githubusercontent.com/assets/1044532/14666098/b1463422-06d7-11e6-8bc0-613f84494a32.png)

**Comment by mohierf** [comment] 2016-04-20 10:07
**Got it !**

Display groups correctly:
![image](https://cloud.githubusercontent.com/assets/2932687/14671050/1a03c1f6-06f0-11e6-9111-365fcd08d61a.png)

Then, cllick on group name with spaces (*note the syntax in the filter search box*):

![image](https://cloud.githubusercontent.com/assets/2932687/14671064/2a85c934-06f0-11e6-928d-876209b0f7e5.png)

And, then, cllick on group name without spaces:

![image](https://cloud.githubusercontent.com/assets/2932687/14671090/4cf934e2-06f0-11e6-9469-21aafc82589e.png)

**Comment by pedrojimenez** [comment] 2016-04-20 12:59
Ohhhh great !! Please push it ... wanna test it :))

**Comment by mohierf** [comment] 2016-04-20 13:23
I push a my current working stuff in my own repo. I will keep you informed when I finish ... I take ooportunity to make some cleaning in groups layout.

**Comment by pedrojimenez** [comment] 2016-04-20 13:42
Thanks again

**Closed** 2016-04-22 12:01 UTC
Labels: enhancement
