### ISSUE TITLE
hostgroups

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#300] opened 2015-08-24 20:01 UTC
Hi,

I test the Hosts groups overview : 
- if the hostgroups is set in the host config file : no problem it's working
- if the hostgroup_members is set in the hostgroup config file : in the webui the hosts groups overview, the group is empty...

**Comment by mohierf** [comment] 2015-08-25 04:37
Are your groups present in the host view?

![image](https://cloud.githubusercontent.com/assets/2932687/9458824/b851871c-4af3-11e5-9707-eb1ed8ff6667.png)


Please post your configuration with this problem.

Mine is:
```
An host:

define host{
   use                  generic-host, shinken2, linux-ssh, important
   host_name            wheezy
   address              127.0.0.1
   alias                Shinken on Debian Wheezy
   display_name         Fred's testing server

   business_impact      3

   hostgroups           servers

   contact_groups       admins

   ...
```

```
An hostgroup:

define hostgroup {
   hostgroup_name  linux   ; The name of the hostgroup
   alias           Linux Servers   ; Long name of the group
   members         wheezy
}
```

And the hosts groups overview is as is:
![image](https://cloud.githubusercontent.com/assets/2932687/9458796/61bd314e-4af3-11e5-8939-764e01390202.png)


`wheezy` is a member of *Linux servers* and *Servers* groups ...

**Comment by b-keller** [comment] 2015-08-26 19:00
hi,
so in th shinken doc (Host Group Definition) : 
members : This is a list of the short names of hosts that should be included in this group.
Multiple host names should be separated by commas. This directive may be used as an alternative to (or in addition to) the hostgroups directive in host definitions.

```define hostgroup{
   hostgroup_name  ESX   
   alias           ESX Hypervisors   
   membersesx1,esx2,esx3
}```

**Comment by mohierf** [comment] 2015-08-27 03:36
Ok, I understand where the problem is ... the Shinken core does not manage correctly the hostgroups members property. This property is used in the configuration phase but does not persist in the objects used by the WebUI ...

I proposed a Pull Request to cope with this problem but I just saw that it has not yet been merged ... even in the last version :/P

My PR: https://github.com/naparuba/shinken/pull/1654

**Comment by maethor** [comment] 2015-08-27 06:21
@mohierf :(

@b-keller In my opinion, using `members` is a bad practice anyway. Because when you add an host, you will have many objects to edit. And when you remove this host you will have to think about removing it from all the objects where it's referenced. If you use `hostgroups` in the host object, you don't have this problem.

**Comment by mohierf** [comment] 2015-08-27 06:43
@maethor : you are right ... but Nagios/Shinken configuration allows this configuration style and Shinken should remain Nagios compatible!

**Comment by maethor** [comment] 2015-08-27 07:05
Yep, I was just giving some advice. But of course Shinken should manage this properly.

**Comment by maethor** [comment] 2015-08-27 14:18
@b-keller can I close this issue?

**Comment by b-keller** [comment] 2015-08-27 14:42
It's ok for me, you have right  about bad and best practice with hosts group. Maybe it needs to be better explained in Shinken Doc...

Thanks




Le Jeudi 27 Août 2015 16:18 CEST, Guillaume Subiron <notifications@github.com> a écrit:
 
@b-keller can I close this issue?

**Closed** 2015-08-27 20:19 UTC
