### ISSUE TITLE
[BS3]Error with  service group 

### ISSUE THREAD

**Issue by olivierHa** [shinken-monitoring/mod-webui#130] opened 2015-05-04 08:23 UTC
Servicegroup isn't working with branch bs3 (and shinken 2.4).

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/Shinken-2.4_rc4-py2.6.egg/shinken/webui/bottlewebui.py", line 686, in _handle
    return callback(**args)
  File "/usr/local/lib/python2.6/dist-packages/Shinken-2.4_rc4-py2.6.egg/shinken/webui/bottlewebui.py", line 1357, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui/module.py", line 557, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.6/dist-packages/Shinken-2.4_rc4-py2.6.egg/shinken/webui/bottlewebui.py", line 2749, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.6/dist-packages/Shinken-2.4_rc4-py2.6.egg/shinken/webui/bottlewebui.py", line 2723, in template
    return TEMPLATES[tpl].render(kwargs)
  File "/usr/local/lib/python2.6/dist-packages/Shinken-2.4_rc4-py2.6.egg/shinken/webui/bottlewebui.py", line 2695, in render
    self.execute(stdout, kwargs)
  File "/usr/local/lib/python2.6/dist-packages/Shinken-2.4_rc4-py2.6.egg/shinken/webui/bottlewebui.py", line 2681, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui/plugins/groups/views/services-groups-overview.tpl", line 139, in <module>
    <span class="{{'font-warning' if hUnreachable > 0 else 'font-greyed'}}">
NameError: name 'hUnreachable' is not defined

**Comment by mohierf** [comment] 2015-05-04 08:44
I will try to reproduce the problem ... it seems that there are some missing lines in your message :;)

**Comment by mayasd** [comment] 2015-05-20 15:21
Hi,
I have same issue (Shinken 2.4). Traceback : 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 686, in _handle
    return callback(**args)
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 1357, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui/module.py", line 559, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 2749, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 2723, in template
    return TEMPLATES[tpl].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 2695, in render
    self.execute(stdout, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 2681, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui/plugins/groups/views/services-groups-overview.tpl", line 139, in <module>
    <span class="{{'font-warning' if hUnreachable > 0 else 'font-greyed'}}">
NameError: name 'hUnreachable' is not defined

**Comment by mohierf** [comment] 2015-05-20 16:44
Did you copy all the Traceback logs ... it seems that there are missing lines at the end ?

**Comment by mayasd** [comment] 2015-05-21 07:12
Argh...it's better now ;)

**Comment by mohierf** [comment] 2015-05-21 07:57
Is it fixed ? If so, I do not understand why ... :/P

**Comment by mayasd** [comment] 2015-05-21 15:49
Sorry, it's not fixed. Look at my first comment, traceback is complete now :)

**Comment by mohierf** [comment] 2015-05-21 16:16
Sorry (also ...) I did not understood your comment ... ok, now I see where the problem should be. I will try to fix very soon ...

**Comment by maethor** [comment] 2015-06-01 11:13
I think we can close this bug, because the line concerned have been removed.

**Closed** 2015-06-01 11:19 UTC
