### ISSUE TITLE
Chrome Column Rendering

### ISSUE THREAD

**Issue by jesseorr** [shinken-monitoring/mod-webui#527] opened 2016-07-14 14:27 UTC
The data laid out in the chrome browser overlaps Output, Duration, and State data, even when on a wide-screen layout. The layout appears to function fine in Firefox and Edge. This started happening when I upgraded WebUI from 2.2.1 to 2.4.2c via shinken.io.

Chrome Version 51.0.2704.103 m (64-bit)
Firefox 47.0
Edge 25.10586.0.0

![chrome-wide](https://cloud.githubusercontent.com/assets/5696766/16843013/68c0da4a-4994-11e6-9522-5404fafbb50e.png)

**Comment by b-keller** [comment] 2016-07-15 07:23
Hi,

I had the same problem with Firefox ESR 45.2.0 :

![capture1](https://cloud.githubusercontent.com/assets/12746104/16865984/39b17568-4a69-11e6-9983-0bd90ef1b0e4.PNG)

and no problem with Chromium 51.0.2704.106...

Today, the problem is gone in firefox ESR after  i 've resized firefox windows from maximized size to windows size... (cache problem ?)

**Comment by mohierf** [comment] 2016-07-15 09:06
Ok, so there is no more problem, or is there still a problem with a particular browser ? It is not clear to me ... :wink:

**Comment by jesseorr** [comment] 2016-07-18 15:41
The issue persists, I am unable to 'fix' the problem after resizing windows in Chrome Version 51.0.2704.106 m (64-bit).

**Comment by maethor** [comment] 2017-05-30 05:24
Sorry for the delay.

@jesseorr @b-keller do you still have the problem? We use shinken webui intensively, and I have never seen this. I can't reproduce.

**Comment by b-keller** [comment] 2018-01-22 19:45
no more problem, you can close it

**Closed as completed** 2018-11-23 11:56 UTC
