### ISSUE TITLE
webui2 error during installation

### ISSUE THREAD

**Issue by satyan01** [shinken-monitoring/mod-webui#564] opened 2017-04-24 09:50 UTC
Hello 

 I install shinken on ubuntu but I have an error during webui2 installation

![image](https://cloud.githubusercontent.com/assets/15144026/25331674/2c4c7e40-28e4-11e7-8979-bad8fcc6ff08.png)

en fait quoi que je veuille installer en tant que shinken j'ai la meme erreur

**Comment by mohierf** [comment] 2017-04-24 10:00
I am sure that the problem is not related to the WebUI package.

IMHO, the problem is almost surely related to the shinken.io repository web site: @naparuba ?

**Comment by satyan01** [comment] 2017-04-24 10:01
I have installed from tarball from shinken website

**Comment by mohierf** [comment] 2017-04-24 10:03
The error happen when you `shinken install webui2`, right? And you say that it happens whatever you try to install with the `shinken` cli ? If so, the problem is related to the shinken.io repository ...

**Comment by satyan01** [comment] 2017-04-24 11:03
What I have to do to fix this issue ?

**Comment by satyan01** [comment] 2017-04-24 11:04
I have to open firewall rules ? if yes on which site ?

**Comment by satyan01** [comment] 2017-04-24 11:27
I asked to open 7767 and 7763 port and github.com/naparuba

**Comment by mohierf** [comment] 2017-04-24 11:54
Opening firewall ports will not fix this. I think that the problem is residing in the application on the shinken.io server and only @naparuba may fix this.

You can avoid using this command and get the files directly from the github repository:
- copy the repo file *etc/modules/webui2.cfg* to your *etc/modules* directory
- copy the directory *module* in your modules directory and rename it as *webui2*

Is is pretty much what the `shinken` cli script does...

**Comment by satyan01** [comment] 2017-04-24 12:01
the /etc/modules/ folder contains only sample.cfg

**Comment by mohierf** [comment] 2017-04-24 12:05
Ok. So you may try what I suggested ...

**Comment by satyan01** [comment] 2017-04-24 12:16
/etc/modules or /etc/shinken/modules ?

**Comment by satyan01** [comment] 2017-04-24 12:39
same result

**Comment by satyan01** [comment] 2017-04-24 12:39
![image](https://cloud.githubusercontent.com/assets/15144026/25337350/ddb839d2-28fb-11e7-960c-2a6358b65137.png)

**Comment by satyan01** [comment] 2017-04-24 14:32
![image](https://cloud.githubusercontent.com/assets/15144026/25342203/8fa36e0a-290b-11e7-93c0-8984ca6a2259.png)

**Comment by mohierf** [comment] 2017-04-24 15:37
Forget the `shinken install` CLI ... it looks buggy as of now.

Get the files directly from the github repository https://github.com/shinken-monitoring/mod-webui:
- copy the *etc/modules/webui2.cfg* to your *etc/shinken/modules* directory
- copy the directory *module* in your */var/lib/shinken/modules* directory and rename it as *webui2*

Is it the first shinken module you are installing?

**Comment by satyan01** [comment] 2017-04-25 07:06
Hello

Yes it is my first installation.

**Comment by satyan01** [comment] 2017-04-25 07:08
open the port have solved the issue but now the message the installation directory/etc/shinken/packs is missing

**Comment by satyan01** [comment] 2017-04-25 07:36
I have reinstalled completely and now I have this message,

![image](https://cloud.githubusercontent.com/assets/15144026/25373603/a626956e-299a-11e7-969d-6879697e6c77.png)


Oh my god Linux is very complicated !

**Comment by mohierf** [comment] 2017-04-25 08:22
Your problem is, AFAIR, a known problem with Shinken installation on recent Linux distros :/

I am closing this issue because the WebUI is not concerned.

Please leave me an email to go on discussing this: frederic.mohier at gmail.com ...

**Closed as completed by mohierf** 2017-04-25 08:22 UTC
