### ISSUE TITLE
Some pages show problems even when in programmed downtime

### ISSUE THREAD

**Issue by vizvayu** [shinken-monitoring/mod-webui#339] opened 2015-09-09 18:15 UTC
Both the currently dashboard and the top-right overall service state window in the regular dashboard show services in critical state even when those services are in programmed downtime. Here are a couple of examples of this behaviour:
![example2](https://cloud.githubusercontent.com/assets/1631074/9770155/e2cd4b30-5704-11e5-8c44-8ef58af27c4c.png)
![example1](https://cloud.githubusercontent.com/assets/1631074/9770263/9235a1da-5705-11e5-811c-ead604756f2e.png)

This seems to be working fine in the "Problems" menu. Here only the real warnings and criticals are displayed:
![example3](https://cloud.githubusercontent.com/assets/1631074/9770177/07cccd48-5705-11e5-89b3-43bbdad79a1b.png)

I'm not completely sure if this is by design or a bug.

**Comment by mohierf** [comment] 2015-09-10 05:29
Sorry but I do not really understand where the problem is ... 

How I interpret your configuration: 
- you have 98 hosts, and all hosts are currently UP amongst them 4 are in a scheduled downtime period
- you have 1107 services, 1105 are UP, 1 is WARNING, 1 is CRITICAL, and 50 are in a scheduled downtime period

 The overall services states indicator only displays 1 problem because only one service W or C is not acknowledged or downtime scheduled. This is what you see in the problems page where the default is to show only not ACK and not DOWNTIME problems ...

 To be more precise, I would need to know the filter you have in the problems page ?

**Comment by vizvayu** [comment] 2015-09-10 13:27
The problem is that the service that shows up in CRITICAL state, actually is in a downtime period, so it shouldn't appear as CRITICAL. That's my opinion of course, maybe this is working as intended, I don't really know.
The filters from the Problems menu are:
isnot:UP isnot:OK isnot:PENDING isnot:ACK isnot:DOWNTIME
And those are fine... I mean, I don't want to see an alert in the dashboard for a host or service that is in programmed downtime.
BTW the service in WARNING state was correct; we had a disk over 90% full :)

**Comment by mohierf** [comment] 2015-09-10 14:31
In fact, the rule is that hosts/services which are ACK/DOWNTIME are still counted for their real state but are not acounted anymore as problems ...

 I understand your reasoning and it is better than what is implemented currently ... I will submit a modification soon

The method datamanager.get_all_problems() is not used anymore in currently view since my last commit ... my bad, I did not removed from the header template :/P 

 This method is an old method that should not be used anywhere at all ...

**Comment by maethor** [comment] 2019-11-18 16:02
Show be fixed now.

**Closed by maethor** 2019-11-18 16:02 UTC
