### ISSUE TITLE
Problems Page (enhancement): When filter result is empty, display the filter bar

### ISSUE THREAD

**Issue by eherot** [shinken-monitoring/mod-webui#550] opened 2016-11-01 21:26 UTC
What happens now:
![screen shot 2016-11-01 at 5 25 04 pm](https://cloud.githubusercontent.com/assets/400447/19908107/26b66668-a058-11e6-8056-b7b785fe1685.png)

This is annoying because you can't simply click back and forth between filters, instead you have to use the back button.

**Comment by mohierf** [comment] 2016-11-02 11:22
You would like to have the filter bar instead of the message, right ? But the filter bar is always available on top of the current page ... why do you need to click back and forth ?

**Comment by eherot** [comment] 2016-11-02 13:42
The filter bar at the top does not allow you to click "back and forth" it only allows you to "view all". See #551 (unless I'm missing something?).

**Comment by eherot** [comment] 2016-11-02 13:44
Actually it would be fine to keep displaying the message, but this thing:
![screen shot 2016-11-02 at 9 43 38 am](https://cloud.githubusercontent.com/assets/400447/19930904/e4bf67bc-a0e0-11e6-83b4-2be63b9573c2.png)
...should appear above it.

**Comment by mohierf** [comment] 2016-11-02 15:01
What I call the filter bar is not your screen capture but the header on top of the page where you can choose filters / bookmarks and type in a filter string ...

**Comment by mohierf** [comment] 2016-11-02 15:02
The message simply indicates that your current filter did not get any result

**Comment by eherot** [comment] 2016-11-02 15:24
Is there a single click you can make in the filter bar that will show you only services in a particular state the way that the bar I screenshotted can do?

**Comment by mohierf** [comment] 2016-11-02 16:45
No, there is not. But you can bookmark a specific filter and then you will retrieve later ...

**Comment by maethor** [comment] 2017-05-29 20:55
@eherot is it a duplicate of #551 ?

**Comment by eherot** [comment] 2017-05-31 14:34
No. This is a request to display the panel even when there are no filter results. #551 is a request to change how the panel itself works.

**Comment by maethor** [comment] 2017-05-31 15:53
OK but the panel depends on the results beyond it. So if there is no filter result, the panel will be completely empty, so kind of useless. Am I wrong ?

**Comment by eherot** [comment] 2017-05-31 17:43
Not quite. Even the empty panel serves a purpose because the icons are also links to different filters.

**Comment by maethor** [comment] 2017-05-31 20:14
OK, I understand now. I will do it.

**Closed as completed** 2017-05-31 20:36 UTC
